"""
Strategy Template for GA-Generated FreqTrade Strategies

Adapted from GAFreqTrade for freqtradeForkGA
"""

STRATEGY_TEMPLATE = '''# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# AUTO-GENERATED STRATEGY - DO NOT EDIT MANUALLY
# Generated by Genetic Algorithm: {generation_date}
# Generation: {generation}
# Individual ID: {individual_id}
# Fitness: {fitness}

import numpy as np
import pandas as pd
from datetime import datetime, timedelta, timezone
from pandas import DataFrame
from typing import Dict, Optional, Union
from functools import reduce

from freqtrade.strategy import (
    IStrategy,
    Trade,
    Order,
    PairLocks,
    informative,
    BooleanParameter,
    CategoricalParameter,
    DecimalParameter,
    IntParameter,
    RealParameter,
    timeframe_to_minutes,
    timeframe_to_next_date,
    timeframe_to_prev_date,
    merge_informative_pair,
    stoploss_from_absolute,
    stoploss_from_open,
)

import talib.abstract as ta
from technical import qtpylib


class {class_name}(IStrategy):
    """
    Auto-generated trading strategy by Genetic Algorithm
    
    Generation: {generation}
    Individual ID: {individual_id}
    Parent IDs: {parent_ids}
    Mutations: {mutations}
    
    Strategy Components:
    {strategy_components}
    """
    
    INTERFACE_VERSION = 3
    
    # Basic settings
    timeframe = "{timeframe}"
    can_short: bool = False
    
    # ROI table - defines minimum ROI over time
    minimal_roi = {minimal_roi}
    
    # Stoploss
    stoploss = {stoploss}
    
    # Trailing stoploss
    trailing_stop = {trailing_stop}
    trailing_stop_positive = {trailing_stop_positive}
    trailing_stop_positive_offset = {trailing_stop_positive_offset}
    trailing_only_offset_is_reached = {trailing_only_offset_is_reached}
    
    # Run "populate_indicators()" only for new candle
    process_only_new_candles = True
    
    # Exit signal settings
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False
    
    # Number of candles the strategy requires before producing valid signals
    startup_candle_count: int = {startup_candle_count}
    
    # Hyperoptable parameters (for manual optimization if needed)
{hyperopt_parameters}
    
    # Order types
    order_types = {{
        "entry": "limit",
        "exit": "limit",
        "stoploss": "market",
        "stoploss_on_exchange": False
    }}
    
    order_time_in_force = {{
        "entry": "GTC",
        "exit": "GTC"
    }}
    
    def informative_pairs(self):
        """
        Define additional informative pair/interval combinations
        """
        return []
    
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Adds technical indicators to the given DataFrame
        
        Indicators used:
{indicator_list}
        """
{indicator_calculations}
        
        return dataframe
    
    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the entry signal for the given dataframe
        
        Entry conditions:
{entry_condition_list}
        """
        conditions = []
        
{entry_conditions}
        
        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'enter_long'
            ] = 1
        
        return dataframe
    
    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """
        Based on TA indicators, populates the exit signal for the given dataframe
        
        Exit conditions:
{exit_condition_list}
        """
        conditions = []
        
{exit_conditions}
        
        if conditions:
            dataframe.loc[
                reduce(lambda x, y: x & y, conditions),
                'exit_long'
            ] = 1
        
        return dataframe
'''


def get_strategy_template() -> str:
    """Return the strategy template string"""
    return STRATEGY_TEMPLATE


def format_strategy_components(indicators, entry_conditions, exit_conditions) -> str:
    """Format strategy components for documentation"""
    components = []
    components.append(f"    - Indicators: {len(indicators)}")
    components.append(f"    - Entry conditions: {len(entry_conditions)}")
    components.append(f"    - Exit conditions: {len(exit_conditions)}")
    return "\n".join(components)
