"""
Null Monitor — No-op fallback when rich is not installed or monitor is disabled.

Implements the same public interface as TerminalMonitor so that
evolution.py can call monitor methods unconditionally.
"""


class NullMonitor:
    """No-op monitor — every callback is a silent pass-through."""

    active: bool = False

    def start(self, config: dict) -> None: ...
    def stop(self) -> None: ...

    # Generation lifecycle
    def on_generation_start(self, gen: int, total: int) -> None: ...
    def on_generation_end(self, gen: int, stats, timing, best_individual, extras: dict | None = None) -> None: ...

    # Phase tracking
    def on_phase_start(self, phase: str) -> None: ...
    def on_phase_end(self, phase: str, elapsed: float = 0.0) -> None: ...

    # Evaluation progress (within a generation)
    def on_eval_progress(self, completed: int, total: int) -> None: ...

    # Events
    def on_new_best(self, individual) -> None: ...
    def on_convergence_warning(self, no_improvement: int, patience: int) -> None: ...
    def on_evolution_complete(self, summary: dict | None = None) -> None: ...
