class Config:
    NOTIFIER_TELEGRAM_CHANNEL_ID_BACKTEST = "-1001569603630"
    NOTIFIER_TELEGRAM_BOT_API_TOKEN_BACKTEST = "914726826:AAEHl2IH3tjXvAwe_hnTcxKjHmRismua0VE"
    
    BACKTEST_DOWNLOADED_JSON_DATA_FILE_PATH = ""
    BACKTEST_DATA_CLEANER_YEAR = 2020
    BACKTEST_DATA_CLEANER_MONTH_INDEX = 9
    IS_BACKTEST = False
    WORKSPACE_PATH = "workspace2" if IS_BACKTEST else "workspace"
    EXECUTION_PATH = "/root/" + WORKSPACE_PATH + "/execution/"
    IS_PARALLER_EXECUTION = True
