FROM freqtradeorg/freqtrade:develop

RUN sudo apt-get update \
    && sudo apt-get -y install git \
    && sudo apt-get clean \
    # The below dependency - pyti - serves as an example. Please use whatever you need!
    && pip install --user pyti
