FROM freqtradeorg/freqtrade:develop

RUN apt-get update \
    && apt-get -y install git \
    && apt-get clean \
    # The below dependency - pyti - serves as an example. Please use whatever you need!
    && pip install pyti
