FROM freqtradeorg/freqtrade:develop_plot


# Pin jupyter-client to avoid tornado version conflict
RUN pip install jupyterlab jupyter-client==7.3.4 --user --no-cache-dir

# Empty the ENTRYPOINT to allow all commands
ENTRYPOINT []
