#!/usr/bin/env python3
"""Generate simple manual-direction research strategies."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_ROOT = REPO_ROOT / "user_data/strategy_research"
GENERATED_DIR = REPO_ROOT / "user_data/strategies/research_generated"
GENERATED_FILE = GENERATED_DIR / "manual_direction_strategies.py"
REGISTRY_PATH = AGENT_ROOT / "experiments/manual_direction_strategy_registry.json"
EXPERIMENT_PATH = AGENT_ROOT / "experiments/manual_direction_experiment.json"
LEDGER_PATH = AGENT_ROOT / "manual_playbook/latest_manual_direction_plan.md"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def build_source() -> str:
    generated_at = utc_stamp()
    return f'''"""Manual-direction research strategies.

Generated by user_data/strategy_research/generate_manual_direction_strategies.py.
Research-only: do not promote without full validation.
"""

from __future__ import annotations

import sys
from datetime import datetime
from pathlib import Path

from pandas import DataFrame
import talib.abstract as ta

sys.path.append(str(Path(__file__).resolve().parents[1]))

from btc_eth_risk_controlled_strategies import BtcEthFuturesRegime10xOneMinuteStrategy


GENERATED_AT_UTC = {generated_at!r}


class ManualDirectionStructureBreakStrategy(BtcEthFuturesRegime10xOneMinuteStrategy):
    """Direction first: BTC/ETH return agreement plus structure break."""

    minimal_roi = {{"180": 0.0, "60": 0.010, "0": 0.018}}
    stoploss = -0.010
    startup_candle_count = 2400

    def leverage(self, pair: str, current_time: datetime, current_rate: float, proposed_leverage: float, max_leverage: float, entry_tag: str | None, side: str, **kwargs) -> float:
        return min(2.0, max_leverage)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["manual_high_4h"] = dataframe["high"].rolling(240).max().shift(1)
        dataframe["manual_low_4h"] = dataframe["low"].rolling(240).min().shift(1)
        dataframe["manual_ret_30m"] = dataframe["close"] / dataframe["close"].shift(30) - 1.0
        dataframe["manual_ema_1h"] = ta.EMA(dataframe, timeperiod=60)
        dataframe["manual_ema_4h"] = ta.EMA(dataframe, timeperiod=240)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        long_direction = (dataframe["ret_24h"] > 0.006) & (dataframe["ret_72h"] > 0.0) & (dataframe["close"] > dataframe["manual_high_4h"])
        short_direction = (dataframe["ret_24h"] < -0.006) & (dataframe["ret_72h"] < 0.0) & (dataframe["close"] < dataframe["manual_low_4h"])
        dataframe.loc[dataframe["risk_allowed"] & long_direction & (dataframe["manual_ret_30m"] > 0.0005) & (dataframe["volume"] > 0), ["enter_long", "enter_tag"]] = (1, "manual_direction_break_long")
        dataframe.loc[dataframe["risk_allowed"] & short_direction & (dataframe["manual_ret_30m"] < -0.0005) & (dataframe["volume"] > 0), ["enter_short", "enter_tag"]] = (1, "manual_direction_break_short")
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[((dataframe["close"] < dataframe["manual_ema_1h"]) | (dataframe["ret_24h"] < 0)) & (dataframe["volume"] > 0), ["exit_long", "exit_tag"]] = (1, "manual_direction_long_invalid")
        dataframe.loc[((dataframe["close"] > dataframe["manual_ema_1h"]) | (dataframe["ret_24h"] > 0)) & (dataframe["volume"] > 0), ["exit_short", "exit_tag"]] = (1, "manual_direction_short_invalid")
        return dataframe


class ManualDirectionBtcLeadEthFollowStrategy(BtcEthFuturesRegime10xOneMinuteStrategy):
    """Direction first: BTC moves, ETH follows after a short delay."""

    minimal_roi = {{"180": 0.0, "45": 0.008, "0": 0.016}}
    stoploss = -0.009
    startup_candle_count = 2400

    def leverage(self, pair: str, current_time: datetime, current_rate: float, proposed_leverage: float, max_leverage: float, entry_tag: str | None, side: str, **kwargs) -> float:
        return min(2.0, max_leverage)

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["manual_ret_15m"] = dataframe["close"] / dataframe["close"].shift(15) - 1.0
        dataframe["manual_ret_60m"] = dataframe["close"] / dataframe["close"].shift(60) - 1.0
        dataframe["manual_btc_proxy"] = dataframe["ret_24h"].shift(15)
        dataframe["manual_ema_2h"] = ta.EMA(dataframe, timeperiod=120)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        long_setup = (dataframe["manual_btc_proxy"] > 0.008) & (dataframe["ret_24h"] > 0.002) & (dataframe["manual_ret_15m"] > 0.0004)
        short_setup = (dataframe["manual_btc_proxy"] < -0.008) & (dataframe["ret_24h"] < -0.002) & (dataframe["manual_ret_15m"] < -0.0004)
        dataframe.loc[dataframe["risk_allowed"] & long_setup & (dataframe["close"] > dataframe["manual_ema_2h"]) & (dataframe["volume"] > 0), ["enter_long", "enter_tag"]] = (1, "manual_btc_lead_long")
        dataframe.loc[dataframe["risk_allowed"] & short_setup & (dataframe["close"] < dataframe["manual_ema_2h"]) & (dataframe["volume"] > 0), ["enter_short", "enter_tag"]] = (1, "manual_btc_lead_short")
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[((dataframe["manual_ret_60m"] < -0.001) | (dataframe["close"] < dataframe["manual_ema_2h"])) & (dataframe["volume"] > 0), ["exit_long", "exit_tag"]] = (1, "manual_btc_lead_long_invalid")
        dataframe.loc[((dataframe["manual_ret_60m"] > 0.001) | (dataframe["close"] > dataframe["manual_ema_2h"])) & (dataframe["volume"] > 0), ["exit_short", "exit_tag"]] = (1, "manual_btc_lead_short_invalid")
        return dataframe
'''


def registry_payload() -> dict[str, Any]:
    strategies = [
        "ManualDirectionStructureBreakStrategy",
        "ManualDirectionBtcLeadEthFollowStrategy",
    ]
    return {
        "generated_at_utc": utc_stamp(),
        "generated_strategy_file": rel(GENERATED_FILE),
        "research_mode": "manual_direction_generation",
        "strategies": [
            {
                "name": name,
                "family": "manual-direction",
                "source": "manual_trade_playbook",
                "hypothesis": "Direction-first signals should beat blind entry timing before complex filters are added.",
                "risk_notes": "Research-only low-leverage futures strategy; requires cost, regime, bias, and walk-forward validation.",
            }
            for name in strategies
        ],
    }


def experiment_payload() -> dict[str, Any]:
    strategies = ["ManualDirectionStructureBreakStrategy", "ManualDirectionBtcLeadEthFollowStrategy"]
    return {
        "id": "manual_direction_strategy_lab",
        "title": "Manual direction layer strategy lab",
        "profile_ref": "strategy_registry.json",
        "strategy_path": "user_data/strategies/research_generated",
        "timeframes": ["1m"],
        "timeranges": ["20240101-20260622"],
        "matrix": {"timeranges": [{"name": "smoke", "label": "Recent smoke", "timerange": "20260101-20260201"}]},
        "fee": 0.0005,
        "strategies": strategies,
        "strategy_groups": {"manual_direction": strategies},
        "checks": {"backtesting": True, "recursive_analysis": False, "lookahead_analysis": False},
        "notes": ["Tests direction before adding discretionary entry-location filters.", "No live or dry-run promotion is implied."],
    }


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(build_source(), encoding="utf-8")
    registry = registry_payload()
    REGISTRY_PATH.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")
    EXPERIMENT_PATH.write_text(json.dumps(experiment_payload(), indent=2, ensure_ascii=False), encoding="utf-8")
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(
        "# Manual Direction Plan\n\n"
        f"- Generated UTC: `{registry['generated_at_utc']}`\n"
        f"- Strategy file: `{registry['generated_strategy_file']}`\n"
        f"- Experiment: `{rel(EXPERIMENT_PATH)}`\n\n"
        "| Strategy | Family | Hypothesis |\n|---|---|---|\n"
        + "\n".join(f"| {item['name']} | {item['family']} | {item['hypothesis']} |" for item in registry["strategies"])
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {rel(GENERATED_FILE)}")
    print(f"Wrote {rel(REGISTRY_PATH)}")
    print(f"Wrote {rel(EXPERIMENT_PATH)}")
    print(f"Wrote {rel(LEDGER_PATH)}")


if __name__ == "__main__":
    main()
