#!/usr/bin/env python3
"""Generate entry-confirmation variants on top of manual direction strategies."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_ROOT = REPO_ROOT / "user_data/strategy_research"
GENERATED_DIR = REPO_ROOT / "user_data/strategies/research_generated"
GENERATED_FILE = GENERATED_DIR / "manual_entry_confirmation_strategies.py"
REGISTRY_PATH = AGENT_ROOT / "experiments/manual_entry_confirmation_strategy_registry.json"
EXPERIMENT_PATH = AGENT_ROOT / "experiments/manual_entry_confirmation_experiment.json"
LEDGER_PATH = AGENT_ROOT / "manual_playbook/latest_manual_entry_confirmation_plan.md"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def build_source() -> str:
    return f'''"""Manual entry-confirmation research strategies.

Generated by user_data/strategy_research/generate_manual_entry_confirmation_strategies.py.
Research-only: do not promote without full validation.
"""

from __future__ import annotations

from pandas import DataFrame
import talib.abstract as ta

from manual_direction_strategies import (
    ManualDirectionStructureBreakStrategy,
    ManualDirectionBtcLeadEthFollowStrategy,
)


GENERATED_AT_UTC = {utc_stamp()!r}


class ManualEntryPullbackResumeStrategy(ManualDirectionStructureBreakStrategy):
    """Direction + pullback to EMA + renewed movement in favor."""

    minimal_roi = {{"180": 0.0, "60": 0.008, "0": 0.014}}
    stoploss = -0.008

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["entry_ema_30m"] = ta.EMA(dataframe, timeperiod=30)
        dataframe["entry_ret_5m"] = dataframe["close"] / dataframe["close"].shift(5) - 1.0
        dataframe["entry_was_near_ema"] = (
            (dataframe["low"].rolling(45).min() <= dataframe["entry_ema_30m"] * 1.0015)
            & (dataframe["high"].rolling(45).max() >= dataframe["entry_ema_30m"] * 0.9985)
        )
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        long_direction = (dataframe["ret_24h"] > 0.006) & (dataframe["ret_72h"] > 0.0) & (dataframe["close"] > dataframe["manual_ema_4h"])
        short_direction = (dataframe["ret_24h"] < -0.006) & (dataframe["ret_72h"] < 0.0) & (dataframe["close"] < dataframe["manual_ema_4h"])
        dataframe.loc[dataframe["risk_allowed"] & long_direction & dataframe["entry_was_near_ema"] & (dataframe["entry_ret_5m"] > 0.00025) & (dataframe["close"] > dataframe["entry_ema_30m"]) & (dataframe["volume"] > 0), ["enter_long", "enter_tag"]] = (1, "manual_entry_pullback_resume_long")
        dataframe.loc[dataframe["risk_allowed"] & short_direction & dataframe["entry_was_near_ema"] & (dataframe["entry_ret_5m"] < -0.00025) & (dataframe["close"] < dataframe["entry_ema_30m"]) & (dataframe["volume"] > 0), ["enter_short", "enter_tag"]] = (1, "manual_entry_pullback_resume_short")
        return dataframe


class ManualEntryBtcLeadDelayedConfirmStrategy(ManualDirectionBtcLeadEthFollowStrategy):
    """BTC lead direction + delayed ETH confirmation before entry."""

    minimal_roi = {{"180": 0.0, "45": 0.007, "0": 0.013}}
    stoploss = -0.008

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["entry_ret_3m"] = dataframe["close"] / dataframe["close"].shift(3) - 1.0
        dataframe["entry_ret_12m"] = dataframe["close"] / dataframe["close"].shift(12) - 1.0
        dataframe["entry_rsi"] = ta.RSI(dataframe, timeperiod=45)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        long_setup = (dataframe["manual_btc_proxy"] > 0.008) & (dataframe["ret_24h"] > 0.002) & (dataframe["entry_ret_12m"] > 0.0005)
        short_setup = (dataframe["manual_btc_proxy"] < -0.008) & (dataframe["ret_24h"] < -0.002) & (dataframe["entry_ret_12m"] < -0.0005)
        dataframe.loc[dataframe["risk_allowed"] & long_setup & (dataframe["entry_ret_3m"] > 0) & dataframe["entry_rsi"].between(44, 70) & (dataframe["volume"] > 0), ["enter_long", "enter_tag"]] = (1, "manual_entry_btc_delay_long")
        dataframe.loc[dataframe["risk_allowed"] & short_setup & (dataframe["entry_ret_3m"] < 0) & dataframe["entry_rsi"].between(30, 58) & (dataframe["volume"] > 0), ["enter_short", "enter_tag"]] = (1, "manual_entry_btc_delay_short")
        return dataframe
'''


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(build_source(), encoding="utf-8")
    strategies = ["ManualEntryPullbackResumeStrategy", "ManualEntryBtcLeadDelayedConfirmStrategy"]
    registry = {
        "generated_at_utc": utc_stamp(),
        "generated_strategy_file": rel(GENERATED_FILE),
        "research_mode": "manual_entry_confirmation_generation",
        "strategies": [
            {
                "name": name,
                "family": "manual-entry-confirmation",
                "source": "manual_trade_playbook",
                "hypothesis": "Direction signals need a separate entry-location confirmation before opening futures trades.",
                "risk_notes": "Research-only low-leverage futures strategy; not eligible for dry-run without full validation.",
            }
            for name in strategies
        ],
    }
    experiment = {
        "id": "manual_entry_confirmation_lab",
        "title": "Manual entry confirmation strategy lab",
        "profile_ref": "strategy_registry.json",
        "strategy_path": "user_data/strategies/research_generated",
        "timeframes": ["1m"],
        "timeranges": ["20240101-20260622"],
        "matrix": {"timeranges": [{"name": "smoke", "label": "Recent smoke", "timerange": "20260101-20260201"}]},
        "fee": 0.0005,
        "strategies": strategies,
        "strategy_groups": {"manual_entry_confirmation": strategies},
        "checks": {"backtesting": True, "recursive_analysis": False, "lookahead_analysis": False},
        "notes": ["Tests entry location/confirmation after direction-only signals failed."],
    }
    REGISTRY_PATH.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")
    EXPERIMENT_PATH.write_text(json.dumps(experiment, indent=2, ensure_ascii=False), encoding="utf-8")
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(
        "# Manual Entry Confirmation Plan\n\n"
        f"- Generated UTC: `{registry['generated_at_utc']}`\n"
        f"- Strategy file: `{registry['generated_strategy_file']}`\n"
        f"- Experiment: `{rel(EXPERIMENT_PATH)}`\n\n"
        "| Strategy | Family | Hypothesis |\n|---|---|---|\n"
        + "\n".join(f"| {item['name']} | {item['family']} | {item['hypothesis']} |" for item in registry["strategies"])
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {rel(GENERATED_FILE)}")
    print(f"Wrote {rel(REGISTRY_PATH)}")
    print(f"Wrote {rel(EXPERIMENT_PATH)}")
    print(f"Wrote {rel(LEDGER_PATH)}")


if __name__ == "__main__":
    main()
