#!/usr/bin/env python3
"""Generate stronger manual-style confirmation strategies."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_ROOT = REPO_ROOT / "user_data/strategy_research"
GENERATED_DIR = REPO_ROOT / "user_data/strategies/research_generated"
GENERATED_FILE = GENERATED_DIR / "manual_strong_confirmation_strategies.py"
REGISTRY_PATH = AGENT_ROOT / "experiments/manual_strong_confirmation_strategy_registry.json"
EXPERIMENT_PATH = AGENT_ROOT / "experiments/manual_strong_confirmation_experiment.json"
LEDGER_PATH = AGENT_ROOT / "manual_playbook/latest_manual_strong_confirmation_plan.md"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def build_source() -> str:
    return f'''"""Manual strong-confirmation research strategies.

Generated by user_data/strategy_research/generate_manual_strong_confirmation_strategies.py.
Research-only: do not promote without full validation.
"""

from __future__ import annotations

from pandas import DataFrame
import talib.abstract as ta

from manual_abstention_strategies import (
    ManualAbstentionPullbackResumeStrategy,
    ManualAbstentionBtcLeadConfirmStrategy,
)


GENERATED_AT_UTC = {utc_stamp()!r}


class ManualStrongRetestResumeStrategy(ManualAbstentionPullbackResumeStrategy):
    """Structure break, retest, and renewed movement in favor."""

    minimal_roi = {{"180": 0.0, "60": 0.007, "0": 0.012}}
    stoploss = -0.0075

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["strong_high_2h"] = dataframe["high"].rolling(120).max().shift(8)
        dataframe["strong_low_2h"] = dataframe["low"].rolling(120).min().shift(8)
        dataframe["strong_ema_20m"] = ta.EMA(dataframe, timeperiod=20)
        dataframe["strong_ret_3m"] = dataframe["close"] / dataframe["close"].shift(3) - 1.0
        dataframe["strong_ret_9m"] = dataframe["close"] / dataframe["close"].shift(9) - 1.0
        dataframe["strong_near_retest_long"] = dataframe["low"].rolling(18).min() <= dataframe["strong_high_2h"] * 1.001
        dataframe["strong_near_retest_short"] = dataframe["high"].rolling(18).max() >= dataframe["strong_low_2h"] * 0.999
        dataframe["strong_three_up"] = (dataframe["close"] > dataframe["close"].shift(1)) & (dataframe["close"].shift(1) > dataframe["close"].shift(2))
        dataframe["strong_three_down"] = (dataframe["close"] < dataframe["close"].shift(1)) & (dataframe["close"].shift(1) < dataframe["close"].shift(2))
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["enter_long"] = 0
        dataframe["enter_short"] = 0
        dataframe["enter_tag"] = None
        long_direction = (dataframe["ret_24h"] > 0.006) & (dataframe["ret_72h"] > 0.0) & (dataframe["close"] > dataframe["strong_high_2h"])
        short_direction = (dataframe["ret_24h"] < -0.006) & (dataframe["ret_72h"] < 0.0) & (dataframe["close"] < dataframe["strong_low_2h"])
        not_chasing_long = dataframe["close"] < dataframe["strong_ema_20m"] * 1.006
        not_chasing_short = dataframe["close"] > dataframe["strong_ema_20m"] * 0.994
        dataframe.loc[
            dataframe["risk_allowed"]
            & dataframe["abstain_tradeable"]
            & long_direction
            & dataframe["strong_near_retest_long"]
            & dataframe["strong_three_up"]
            & (dataframe["strong_ret_9m"] > 0.0004)
            & not_chasing_long
            & (dataframe["volume"] > 0),
            ["enter_long", "enter_tag"],
        ] = (1, "strong_retest_resume_long")
        dataframe.loc[
            dataframe["risk_allowed"]
            & dataframe["abstain_tradeable"]
            & short_direction
            & dataframe["strong_near_retest_short"]
            & dataframe["strong_three_down"]
            & (dataframe["strong_ret_9m"] < -0.0004)
            & not_chasing_short
            & (dataframe["volume"] > 0),
            ["enter_short", "enter_tag"],
        ] = (1, "strong_retest_resume_short")
        return dataframe


class ManualStrongFailedBreakoutReversalStrategy(ManualAbstentionBtcLeadConfirmStrategy):
    """Trade only after a failed breakout and reversal confirmation."""

    minimal_roi = {{"150": 0.0, "45": 0.006, "0": 0.011}}
    stoploss = -0.0065

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["strong_high_90m"] = dataframe["high"].rolling(90).max().shift(1)
        dataframe["strong_low_90m"] = dataframe["low"].rolling(90).min().shift(1)
        dataframe["strong_mid_30m"] = dataframe["close"].rolling(30).mean()
        dataframe["strong_ret_6m"] = dataframe["close"] / dataframe["close"].shift(6) - 1.0
        dataframe["strong_failed_up"] = (dataframe["high"].rolling(12).max() > dataframe["strong_high_90m"] * 1.001) & (dataframe["close"] < dataframe["strong_high_90m"])
        dataframe["strong_failed_down"] = (dataframe["low"].rolling(12).min() < dataframe["strong_low_90m"] * 0.999) & (dataframe["close"] > dataframe["strong_low_90m"])
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe["enter_long"] = 0
        dataframe["enter_short"] = 0
        dataframe["enter_tag"] = None
        long_confirm = dataframe["strong_failed_down"] & (dataframe["strong_ret_6m"] > 0.0003) & (dataframe["close"] > dataframe["strong_mid_30m"])
        short_confirm = dataframe["strong_failed_up"] & (dataframe["strong_ret_6m"] < -0.0003) & (dataframe["close"] < dataframe["strong_mid_30m"])
        dataframe.loc[
            dataframe["risk_allowed"]
            & dataframe["abstain_tradeable"]
            & (dataframe["manual_btc_proxy"] > 0)
            & long_confirm
            & (dataframe["volume"] > 0),
            ["enter_long", "enter_tag"],
        ] = (1, "strong_failed_breakout_long")
        dataframe.loc[
            dataframe["risk_allowed"]
            & dataframe["abstain_tradeable"]
            & (dataframe["manual_btc_proxy"] < 0)
            & short_confirm
            & (dataframe["volume"] > 0),
            ["enter_short", "enter_tag"],
        ] = (1, "strong_failed_breakout_short")
        return dataframe
'''


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(build_source(), encoding="utf-8")
    strategies = ["ManualStrongRetestResumeStrategy", "ManualStrongFailedBreakoutReversalStrategy"]
    registry = {
        "generated_at_utc": utc_stamp(),
        "generated_strategy_file": rel(GENERATED_FILE),
        "research_mode": "manual_strong_confirmation_generation",
        "strategies": [
            {
                "name": name,
                "family": "manual-strong-confirmation",
                "source": "manual_trade_playbook",
                "hypothesis": "Strong confirmation should require retest or failed-breakout evidence before entry, not only same-direction returns.",
                "risk_notes": "Research-only futures strategy; requires full validation before any dry-run consideration.",
            }
            for name in strategies
        ],
    }
    experiment = {
        "id": "manual_strong_confirmation_lab",
        "title": "Manual strong confirmation lab",
        "profile_ref": "strategy_registry.json",
        "strategy_path": "user_data/strategies/research_generated",
        "timeframes": ["1m"],
        "timeranges": ["20240101-20260622"],
        "matrix": {"timeranges": [{"name": "smoke", "label": "Recent smoke", "timerange": "20260101-20260201"}]},
        "fee": 0.0005,
        "strategies": strategies,
        "strategy_groups": {"manual_strong_confirmation": strategies},
        "checks": {"backtesting": True, "recursive_analysis": False, "lookahead_analysis": False},
        "notes": ["Tests retest/failed-breakout confirmation before entry."],
    }
    REGISTRY_PATH.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")
    EXPERIMENT_PATH.write_text(json.dumps(experiment, indent=2, ensure_ascii=False), encoding="utf-8")
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(
        "# Manual Strong Confirmation Plan\n\n"
        f"- Generated UTC: `{registry['generated_at_utc']}`\n"
        f"- Strategy file: `{registry['generated_strategy_file']}`\n"
        f"- Experiment: `{rel(EXPERIMENT_PATH)}`\n\n"
        "| Strategy | Family | Hypothesis |\n|---|---|---|\n"
        + "\n".join(f"| {item['name']} | {item['family']} | {item['hypothesis']} |" for item in registry["strategies"])
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {rel(GENERATED_FILE)}")
    print(f"Wrote {rel(REGISTRY_PATH)}")
    print(f"Wrote {rel(EXPERIMENT_PATH)}")
    print(f"Wrote {rel(LEDGER_PATH)}")


if __name__ == "__main__":
    main()
