#!/usr/bin/env python3
"""Generate directed strategy variants from the latest entry-quality review."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_ROOT = REPO_ROOT / "user_data/strategy_research"
REVIEW_PATH = AGENT_ROOT / "entry_quality/latest_entry_quality_review.json"
GENERATED_DIR = REPO_ROOT / "user_data/strategies/research_generated"
GENERATED_FILE = GENERATED_DIR / "entry_quality_strategies.py"
REGISTRY_PATH = AGENT_ROOT / "experiments/entry_quality_strategy_registry.json"
EXPERIMENT_PATH = AGENT_ROOT / "experiments/entry_quality_experiment.json"
LEDGER_PATH = AGENT_ROOT / "entry_quality/latest_directed_experiment_plan.md"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def selected_reviews(review: dict[str, Any]) -> list[dict[str, Any]]:
    selected = []
    for item in review.get("reviews", []):
        if item.get("action") in {"careful_expand", "tighten_or_split", "direction_split"}:
            selected.append(item)
    return selected


def variant_specs(review: dict[str, Any]) -> list[dict[str, Any]]:
    specs = []
    actions = {item.get("strategy"): item for item in selected_reviews(review)}
    if "SampleAutoDefensiveFlatFilterBalancedStrategy" in actions:
        specs.append(
            {
                "name": "EntryQualityDefensiveShortCarefulExpandStrategy",
                "base": "SampleAutoDefensiveFlatFilterBalancedStrategy",
                "family": "entry-quality-careful-expand",
                "action": "careful_expand",
                "body": [
                    '    minimal_roi = {"180": 0.0, "60": 0.0035, "0": 0.007}',
                    "    stoploss = -0.0065",
                    "",
                    "    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:",
                    "        dataframe = super().populate_entry_trend(dataframe, metadata)",
                    '        calm = (dataframe["atr_pct"] < 0.010) & (dataframe["realized_vol_24h"] < 0.072)',
                    '        directional = dataframe["minus_di"] >= dataframe["plus_di"]',
                    '        dataframe.loc[(dataframe["risk_allowed"] & calm & dataframe["trend_down_regime"] & directional & (dataframe["close"] < dataframe["auto_ema_mid"]) & dataframe["auto_rsi"].between(28, 60) & (dataframe["volume"] > 0)), ["enter_short", "enter_tag"]] = (1, "eq_defensive_short_expand")',
                    "        return dataframe",
                ],
            }
        )
    if "SampleAutoTrendPullbackBalancedStrategy" in actions:
        specs.append(
            {
                "name": "EntryQualityTrendShortTightSplitStrategy",
                "base": "SampleAutoTrendPullbackBalancedStrategy",
                "family": "entry-quality-tighten-split",
                "action": "tighten_or_split",
                "body": [
                    '    minimal_roi = {"180": 0.0, "45": 0.0045, "0": 0.010}',
                    "    stoploss = -0.0085",
                    "",
                    "    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:",
                    "        dataframe = super().populate_entry_trend(dataframe, metadata)",
                    '        directional = dataframe["minus_di"] > dataframe["plus_di"] * 1.04',
                    '        dataframe.loc[(dataframe["risk_allowed"] & dataframe["trend_down_regime"] & directional & (dataframe["close"] < dataframe["auto_ema_slow"]) & (dataframe["close"] < dataframe["auto_ema_fast"]) & dataframe["auto_pullback_short"] & (dataframe["auto_ret_15m"] < -0.00025) & dataframe["auto_rsi"].between(30, 56) & (dataframe["volume"] > 0)), ["enter_short", "enter_tag"]] = (1, "eq_trend_short_tight")',
                    "        return dataframe",
                ],
            }
        )
    return specs


def build_source(specs: list[dict[str, Any]]) -> str:
    lines = [
        '"""Entry-quality directed research strategies.',
        "",
        "Generated by user_data/strategy_research/generate_entry_quality_strategies.py.",
        "Research-only: do not promote without full validation.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from pandas import DataFrame",
        "",
        "from sample_expansion_strategies import (",
        "    SampleAutoDefensiveFlatFilterBalancedStrategy,",
        "    SampleAutoTrendPullbackBalancedStrategy,",
        ")",
        "",
        f"GENERATED_AT_UTC = {utc_stamp()!r}",
        "",
    ]
    for item in specs:
        lines.extend([f"class {item['name']}({item['base']}):", f'    """Directed from entry-quality action: {item["action"]}."""'])
        lines.extend(item["body"])
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> None:
    if REVIEW_PATH.exists():
        review = load_json(REVIEW_PATH)
    else:
        review = {
            "reviews": [
                {"strategy": "SampleAutoDefensiveFlatFilterBalancedStrategy", "action": "careful_expand"},
                {"strategy": "SampleAutoTrendPullbackBalancedStrategy", "action": "tighten_or_split"},
            ]
        }
    specs = variant_specs(review)
    if not specs:
        review = {
            "reviews": [
                {"strategy": "SampleAutoDefensiveFlatFilterBalancedStrategy", "action": "careful_expand"},
                {"strategy": "SampleAutoTrendPullbackBalancedStrategy", "action": "tighten_or_split"},
            ]
        }
        specs = variant_specs(review)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(build_source(specs), encoding="utf-8")
    registry = {
        "generated_at_utc": utc_stamp(),
        "source_review": rel(REVIEW_PATH),
        "generated_strategy_file": rel(GENERATED_FILE),
        "research_mode": "entry_quality_directed_generation",
        "strategies": [
            {
                "name": item["name"],
                "base_strategy": item["base"],
                "family": item["family"],
                "source": "entry_quality_review",
                "action": item["action"],
                "hypothesis": "Use entry-quality diagnosis to test one targeted modification instead of broad random threshold changes.",
                "risk_notes": "Research-only; full cost, matrix, bias, and walk-forward validation required.",
            }
            for item in specs
        ],
    }
    experiment = {
        "id": "entry_quality_directed_strategy_lab",
        "title": "Entry-quality directed strategy variants",
        "profile_ref": "strategy_registry.json",
        "strategy_path": "user_data/strategies/research_generated",
        "timeframes": ["1m"],
        "timeranges": ["20240101-20260622"],
        "matrix": {
            "timeranges": [
                {"name": "smoke", "label": "Recent smoke", "timerange": "20260101-20260622"},
                {"name": "full", "label": "Full local sample", "timerange": "20240101-20260622"},
            ]
        },
        "fee": 0.0005,
        "strategies": [item["name"] for item in specs],
        "strategy_groups": {"entry_quality_directed": [item["name"] for item in specs]},
        "checks": {"backtesting": True, "recursive_analysis": False, "lookahead_analysis": False},
        "notes": [
            "Generated from entry-quality review actions.",
            "Negative-edge strategies are skipped instead of force-optimized.",
        ],
    }
    REGISTRY_PATH.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")
    EXPERIMENT_PATH.write_text(json.dumps(experiment, indent=2, ensure_ascii=False), encoding="utf-8")
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(
        "# Entry Quality Directed Experiment Plan\n\n"
        f"- Generated UTC: `{registry['generated_at_utc']}`\n"
        f"- Source review: `{registry['source_review']}`\n"
        f"- Experiment: `{rel(EXPERIMENT_PATH)}`\n\n"
        "| Strategy | Base | Action | Family |\n|---|---|---|---|\n"
        + "\n".join(
            f"| {item['name']} | {item['base_strategy']} | {item['action']} | {item['family']} |"
            for item in registry["strategies"]
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {rel(GENERATED_FILE)}")
    print(f"Wrote {rel(REGISTRY_PATH)}")
    print(f"Wrote {rel(EXPERIMENT_PATH)}")
    print(f"Wrote {rel(LEDGER_PATH)}")


if __name__ == "__main__":
    main()
