#!/usr/bin/env python3
"""Generate no-trade/abstention variants for manual-style strategies."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_ROOT = REPO_ROOT / "user_data/strategy_research"
GENERATED_DIR = REPO_ROOT / "user_data/strategies/research_generated"
GENERATED_FILE = GENERATED_DIR / "manual_abstention_strategies.py"
REGISTRY_PATH = AGENT_ROOT / "experiments/manual_abstention_strategy_registry.json"
EXPERIMENT_PATH = AGENT_ROOT / "experiments/manual_abstention_experiment.json"
LEDGER_PATH = AGENT_ROOT / "manual_playbook/latest_manual_abstention_plan.md"


def utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def build_source() -> str:
    return f'''"""Manual abstention research strategies.

Generated by user_data/strategy_research/generate_manual_abstention_strategies.py.
Research-only: do not promote without full validation.
"""

from __future__ import annotations

from pandas import DataFrame

from manual_entry_confirmation_strategies import (
    ManualEntryPullbackResumeStrategy,
    ManualEntryBtcLeadDelayedConfirmStrategy,
)


GENERATED_AT_UTC = {utc_stamp()!r}


class ManualAbstentionPullbackResumeStrategy(ManualEntryPullbackResumeStrategy):
    """Manual entry strategy with explicit no-trade filter."""

    minimal_roi = {{"180": 0.0, "60": 0.008, "0": 0.014}}
    stoploss = -0.008

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["abstain_noise"] = dataframe["close"].pct_change().abs().rolling(30).mean()
        dataframe["abstain_direction_agree_long"] = (dataframe["ret_24h"] > 0) & (dataframe["ret_72h"] > -0.003)
        dataframe["abstain_direction_agree_short"] = (dataframe["ret_24h"] < 0) & (dataframe["ret_72h"] < 0.003)
        dataframe["abstain_tradeable"] = (dataframe["abstain_noise"] < 0.0018) & (dataframe["atr_pct"] < 0.010)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_entry_trend(dataframe, metadata)
        long_keep = dataframe["abstain_tradeable"] & dataframe["abstain_direction_agree_long"]
        short_keep = dataframe["abstain_tradeable"] & dataframe["abstain_direction_agree_short"]
        dataframe.loc[dataframe.get("enter_long", 0).fillna(0).astype(bool) & ~long_keep, ["enter_long", "enter_tag"]] = (0, None)
        dataframe.loc[dataframe.get("enter_short", 0).fillna(0).astype(bool) & ~short_keep, ["enter_short", "enter_tag"]] = (0, None)
        dataframe.loc[dataframe.get("enter_long", 0).fillna(0).astype(bool), "enter_tag"] = "manual_abstain_pullback_long"
        dataframe.loc[dataframe.get("enter_short", 0).fillna(0).astype(bool), "enter_tag"] = "manual_abstain_pullback_short"
        return dataframe


class ManualAbstentionBtcLeadConfirmStrategy(ManualEntryBtcLeadDelayedConfirmStrategy):
    """BTC-lead strategy with disagreement/noise abstention."""

    minimal_roi = {{"180": 0.0, "45": 0.007, "0": 0.013}}
    stoploss = -0.008

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_indicators(dataframe, metadata)
        dataframe["abstain_noise"] = dataframe["close"].pct_change().abs().rolling(45).mean()
        dataframe["abstain_disagreement"] = (dataframe["manual_btc_proxy"] * dataframe["ret_24h"]) < 0
        dataframe["abstain_tradeable"] = (dataframe["abstain_noise"] < 0.0016) & ~dataframe["abstain_disagreement"] & (dataframe["atr_pct"] < 0.010)
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe = super().populate_entry_trend(dataframe, metadata)
        dataframe.loc[dataframe.get("enter_long", 0).fillna(0).astype(bool) & ~dataframe["abstain_tradeable"], ["enter_long", "enter_tag"]] = (0, None)
        dataframe.loc[dataframe.get("enter_short", 0).fillna(0).astype(bool) & ~dataframe["abstain_tradeable"], ["enter_short", "enter_tag"]] = (0, None)
        dataframe.loc[dataframe.get("enter_long", 0).fillna(0).astype(bool), "enter_tag"] = "manual_abstain_btc_lead_long"
        dataframe.loc[dataframe.get("enter_short", 0).fillna(0).astype(bool), "enter_tag"] = "manual_abstain_btc_lead_short"
        return dataframe
'''


def main() -> None:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    GENERATED_FILE.write_text(build_source(), encoding="utf-8")
    strategies = ["ManualAbstentionPullbackResumeStrategy", "ManualAbstentionBtcLeadConfirmStrategy"]
    registry = {
        "generated_at_utc": utc_stamp(),
        "generated_strategy_file": rel(GENERATED_FILE),
        "research_mode": "manual_abstention_generation",
        "strategies": [
            {
                "name": name,
                "family": "manual-abstention",
                "source": "manual_trade_playbook",
                "hypothesis": "Skipping noisy or disagreeing windows should improve PF versus always trading direction signals.",
                "risk_notes": "Research-only futures strategy; abstention is not a promotion gate by itself.",
            }
            for name in strategies
        ],
    }
    experiment = {
        "id": "manual_abstention_lab",
        "title": "Manual abstention no-trade filter lab",
        "profile_ref": "strategy_registry.json",
        "strategy_path": "user_data/strategies/research_generated",
        "timeframes": ["1m"],
        "timeranges": ["20240101-20260622"],
        "matrix": {"timeranges": [{"name": "smoke", "label": "Recent smoke", "timerange": "20260101-20260201"}]},
        "fee": 0.0005,
        "strategies": strategies,
        "strategy_groups": {"manual_abstention": strategies},
        "checks": {"backtesting": True, "recursive_analysis": False, "lookahead_analysis": False},
        "notes": ["Tests the human-like ability to skip bad market states."],
    }
    REGISTRY_PATH.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding="utf-8")
    EXPERIMENT_PATH.write_text(json.dumps(experiment, indent=2, ensure_ascii=False), encoding="utf-8")
    LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    LEDGER_PATH.write_text(
        "# Manual Abstention Plan\n\n"
        f"- Generated UTC: `{registry['generated_at_utc']}`\n"
        f"- Strategy file: `{registry['generated_strategy_file']}`\n"
        f"- Experiment: `{rel(EXPERIMENT_PATH)}`\n\n"
        "| Strategy | Family | Hypothesis |\n|---|---|---|\n"
        + "\n".join(f"| {item['name']} | {item['family']} | {item['hypothesis']} |" for item in registry["strategies"])
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {rel(GENERATED_FILE)}")
    print(f"Wrote {rel(REGISTRY_PATH)}")
    print(f"Wrote {rel(EXPERIMENT_PATH)}")
    print(f"Wrote {rel(LEDGER_PATH)}")


if __name__ == "__main__":
    main()
