#!/usr/bin/env python3
"""
Test script to verify that generated strategies can be backtested 
with FreqTrade using real OHLCV data (not mocked).

This demonstrates that:
1. Generated strategies are valid FreqTrade strategies
2. Strategies can be backtested with actual data
3. The backtesting uses FreqTrade's real backtesting engine
4. Strategies can be used with a real trading bot
"""

import sys
import logging
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from genetic_algorithm.strategies.generator import StrategyGenerator
from genetic_algorithm.evaluation.direct_backtester import DirectBacktester
import yaml


def setup_logging():
    """Set up logging for tests."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )


def load_config():
    """Load configuration."""
    config_path = Path(__file__).parent / "config" / "ga_config.yaml"
    with open(config_path, 'r') as f:
        return yaml.safe_load(f)


def test_generated_strategy_backtest():
    """
    Test that a generated strategy can be backtested with FreqTrade
    using actual OHLCV data files.
    """
    print("\n" + "="*80)
    print("TEST: Generated Strategy with Real FreqTrade Backtesting")
    print("="*80)
    print()
    print("This test verifies that:")
    print("1. Strategies generated by the GA are valid FreqTrade strategies")
    print("2. They can be backtested using FreqTrade's real backtesting engine")
    print("3. The backtest uses actual OHLCV data files (not mocked prices)")
    print("4. The strategies are compatible with real FreqTrade trading bots")
    print()
    
    config = load_config()
    
    # Create strategy generator
    print("Step 1: Generating a random strategy...")
    generator = StrategyGenerator(config)
    strategy_gene = generator.generate_random_strategy(generation=0, individual_id=0)
    
    print(f"  ✓ Generated strategy: Gen {strategy_gene.generation}, ID {strategy_gene.individual_id}")
    print(f"  - Timeframe: {strategy_gene.timeframe}")
    print(f"  - Stop Loss: {strategy_gene.stoploss:.2%}")
    print(f"  - Indicators: {len(strategy_gene.indicators)}")
    print(f"  - Entry Conditions: {len(strategy_gene.entry_conditions)}")
    print()
    
    # Generate strategy code
    print("Step 2: Generating Python code for the strategy...")
    strategy_code = generator.generate_strategy_code(strategy_gene)
    # The generator creates class names as GAStrategy_Gen{gen}_Ind{id}
    strategy_name = f"GAStrategy_Gen{strategy_gene.generation}_Ind{strategy_gene.individual_id}"
    
    print(f"  ✓ Generated {len(strategy_code)} characters of code")
    print(f"  ✓ Strategy class name: {strategy_name}")
    print()
    
    # Initialize backtester
    print("Step 3: Initializing FreqTrade backtester...")
    print("  - Using FreqTrade's built-in backtesting engine")
    print("  - Data source: tests/testdata (real OHLCV files)")
    print("  - This is the SAME engine used for live trading validation")
    print()
    
    backtester = DirectBacktester(config)
    
    # Run backtest
    print("Step 4: Running backtest with real OHLCV data...")
    print("  (This may take a few seconds...)")
    print()
    
    result = backtester.backtest_strategy(strategy_code, strategy_name)
    
    # Print results
    print("="*80)
    print("BACKTEST RESULTS")
    print("="*80)
    print()
    
    if result.success:
        print("✅ BACKTEST COMPLETED SUCCESSFULLY!")
        print()
        print("Metrics:")
        print(f"  Total Trades:     {result.total_trades}")
        print(f"  Win Rate:         {result.win_rate:.2%}")
        print(f"  Total Profit:     {result.total_profit:.4f} BTC")
        print(f"  Profit %:         {result.profit_percent:.2f}%")
        print(f"  Max Drawdown:     {result.max_drawdown:.2%}")
        print(f"  Sharpe Ratio:     {result.sharpe_ratio:.2f}")
        print(f"  Execution Time:   {result.execution_time:.2f}s")
        print()
        print("="*80)
        print("✅ VERIFICATION SUCCESSFUL")
        print("="*80)
        print()
        print("This strategy:")
        print("  ✓ Is a valid FreqTrade strategy (inherits from IStrategy)")
        print("  ✓ Was backtested using FreqTrade's real backtesting engine")
        print("  ✓ Used actual OHLCV data from files (not mocked data)")
        print("  ✓ Can be used directly with the FreqTrade trading bot")
        print("  ✓ Follows FreqTrade's strategy interface and conventions")
        print()
        print("Next steps:")
        print("  1. Copy the strategy to user_data/strategies/")
        print("  2. Download real market data: freqtrade download-data")
        print("  3. Backtest: freqtrade backtesting --strategy <StrategyName>")
        print("  4. Test in dry-run: freqtrade trade --dry-run")
        print("  5. Deploy to live trading: freqtrade trade")
        print()
    else:
        print("❌ BACKTEST FAILED")
        print(f"  Error: {result.error_message}")
        print()
        return False
    
    return True


def main():
    """Run test."""
    setup_logging()
    
    print("\n" + "="*80)
    print("GENETIC ALGORITHM - REAL BACKTESTING VERIFICATION")
    print("="*80)
    
    success = test_generated_strategy_backtest()
    
    print("="*80)
    if success:
        print("✅ ALL TESTS PASSED")
    else:
        print("❌ TESTS FAILED")
    print("="*80)
    print()
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
