name: Devcontainer Pre-Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"
  # push:
  #   branches:
  #     - "master"
  #   tags:
  #     - "v*.*.*"
  #   pull_requests:
  #     branches:
  #       - "master"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push:
    name: "Build and Push Devcontainer Image"
    permissions:
      packages: write  # Needed to push package versions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Login to GitHub Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
      with:
        subFolder: .github
        imageName: ghcr.io/${{ github.repository }}-devcontainer
        cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
        push: always


  packages-cleanup:
    name: "Docker Package Cleanup"
    uses: ./.github/workflows/packages-cleanup.yml
    # Only run on push, schedule, or release events
    if: (github.event_name == 'push' || github.event_name == 'schedule') && github.repository == 'freqtrade/freqtrade'
    permissions:
      packages: write # Needed to delete package versions
    with:
      package_name: 'freqtrade-devcontainer'
