name: Update Docker Hub Description
on:
  push:
    branches:
    - stable
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# disable permissions for all of the available permissions
permissions: {}

jobs:
  dockerHubDescription:
    name: "Update Docker Hub Description"
    runs-on: ubuntu-latest
    environment:
      name: docker
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: freqtradeorg/freqtrade
