name: Pre-commit auto-update

on:
  schedule:
    - cron: "13 1 * * 2"
  # on demand
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  auto-update:
    name: Auto-update pre-commit hooks
    runs-on: ubuntu-latest
    environment:
      name: develop

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Install uv and Python 🐍
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        activate-environment: true
        python-version: "3.13"

    - name: Install pre-commit
      run: uv pip install $(grep -E "^pre-commit==" requirements-dev.txt)

    - name: Run auto-update
      run: pre-commit autoupdate

    - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        add-paths: .pre-commit-config.yaml
        labels: |
          Tech maintenance
          Dependencies
        branch: update/pre-commit-hooks
        title: Update pre-commit hooks
        commit-message: "chore: update pre-commit hooks"
        committer: Freqtrade Bot <154552126+freqtrade-bot@users.noreply.github.com>
        author: Freqtrade Bot <154552126+freqtrade-bot@users.noreply.github.com>
        body: Update versions of pre-commit hooks to latest version.
        delete-branch: true
